version: '3'
services:
    web:
        build: .
        volumes:
            - .:/app
        environment:
            SECRET_KEY: secret_key
        ports:
            - '80:80'
        depends_on:
            - db
        working_dir: /app
        command: python ./manage.py runserver 0.0.0.0:80
    db:
        image: postgres:alpine
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
